# Generated by Django 5.2.5 on 2025-10-11 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('Daily', 'Diario'), ('Weekly', 'Semanal')], max_length=20)),
                ('priority', models.TextField(choices=[('Low', 'Baja'), ('Medium', 'Media'), ('High', 'Alta'), ('Very high', 'Muy alta')], help_text='Prioridad del habito')),
                ('target_minutes', models.PositiveIntegerField(help_text='Duracion en minutos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habit_execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField()),
                ('status', models.CharField(choices=[('Completed', 'Completada'), ('Stand by', 'Pendiente'), ('Skipped', 'Omitida'), ('Not executed', 'Sin ejecutarse')], default='Not executed', max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModelUser_executions', to=settings.AUTH_USER_MODEL)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits_executions', to='Habits.habits')),
            ],
        ),
        migrations.AddIndex(
            model_name='habits',
            index=models.Index(fields=['user', 'is_active', 'title', 'created_at'], name='Habits_habi_user_id_1035e9_idx'),
        ),
        migrations.AddIndex(
            model_name='habit_execution',
            index=models.Index(fields=['user', 'execution_date'], name='Habits_habi_user_id_c0b1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='habit_execution',
            index=models.Index(fields=['habit', 'execution_date'], name='Habits_habi_habit_i_362f7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habit_execution',
            unique_together={('user', 'habit', 'execution_date', 'status')},
        ),
    ]
