# Generated by Django 5.2.5 on 2025-10-11 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('energy_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_notes', models.TextField(blank=True, help_text='Como estuvo tu habito hoy')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Horas de sueño de la noche anterior', max_digits=3, null=True)),
                ('stress_trigger', models.CharField(blank=True, choices=[('Fitness', 'Entrenamiento Físico'), ('Health', 'Salud y Bienestar'), ('Learning', 'Lectura y Aprendizaje'), ('Work', 'Productividad Laboral'), ('Creativity', 'Creatividad y Arte'), ('Mindfulness', 'Mindfulness y Meditación'), ('Social', 'Relaciones Sociales'), ('Finance', 'Finanzas Personales')], help_text='¿Que area te esta generando estrés hoy?', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
