# Generated by Django 5.2.5 on 2025-10-11 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Beginner', 'Principiante'), ('Intermediate', 'Intermedio'), ('Advanced', 'Avanzado'), ('Athlete', 'Deportista Alto Rendimiento'), ('Professional', 'Profesional Ocupado'), ('Student', 'Estudiante')], max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_focus_area', models.CharField(choices=[('Fitness', 'Entrenamiento Físico'), ('Health', 'Salud y Bienestar'), ('Learning', 'Lectura y Aprendizaje'), ('Work', 'Productividad Laboral'), ('Creativity', 'Creatividad y Arte'), ('Mindfulness', 'Mindfulness y Meditación'), ('Social', 'Relaciones Sociales'), ('Finance', 'Finanzas Personales')], max_length=100)),
                ('secondary_focus_area', models.JSONField(blank=True, default=list, help_text='Otras areas de foco')),
                ('daily_time_availability', models.CharField(choices=[('low', 'Poco tiempo (< 1 hora/día)'), ('medium', 'Tiempo moderado (1-3 horas/día)'), ('high', 'Mucho tiempo (> 3 horas/día)'), ('flexible', 'Horario flexible')], max_length=100)),
                ('preferred_morning_time', models.TimeField(blank=True, help_text='Horas preferidas por la mañana', null=True)),
                ('preferred_evening_time', models.TimeField(blank=True, help_text='Horas preferidas por la tarde', null=True)),
                ('motivation_level', models.IntegerField(help_text='Nivel de motivacion de 1 ha 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('user_objective', models.TextField(help_text='Objetivos principales del usuario')),
                ('experience_level_user', models.IntegerField(default=1, help_text='Nivel de experiencia del usuario', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
